spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/study_schedule?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: false #show sql

jwt:
  secret: Yp2Pa88z8dKEWN7tXos3YgtclBbi2G4gUOoK86FqvrZvUF5rw2
  access_token:
    expired: 1800000 # 30 min
  refresh_token:
    expired: 604800000 # 7 days


logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

security:
  login-processing-url: /api/login
  username-parameter: memberId
  password-parameter: password
