spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/study_schedule?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: false #show sql
